version: '3'

networks:
  votenet:
    driver: overlay

services:

  assessor:
    image: subfuzion/auditor
    networks:
      votenet:
        aliases:
          - auditor

  database:
    image: mongo:3.4
    networks:
      votenet:
        aliases:
          - database
    ports:
      - "27017:27017"
    volumes:
    - /home/docker/data/db:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
  queue:
    image: redis:3.2
    networks:
      votenet:
        aliases:
          - queue
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: '[ $$(redis-cli ping) = "PONG" ] || exit 1 ]'
      timeout: 2s
      interval: 5s
      retries: 5

  worker:
    image: bootcamps/vote-worker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - votenet
    deploy:
      placement:
        constraints: [node.role == worker]

  vote:
    image: bootcamps/vote
    networks:
      votenet:
        aliases:
          - vote
    ports:
      - "5000:3000"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      votenet:
        aliases:
          - visualizer
